# Generated by Django 2.1.2 on 2018-10-06 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dat_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='isLoggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
